import type { NewsItem, MarketIndex, StockPick, VideoContent, CommunityPost } from './types'

export const mockNews: NewsItem[] = [
  {
    id: '1',
    title: 'Safaricom Reports Strong Q3 Earnings, M-Pesa Revenue Grows 18%',
    source: 'Business Daily',
    summary: 'Kenya largest telco posts impressive quarterly results driven by mobile money growth and data revenue expansion across East Africa.',
    url: '#',
    imageUrl: 'https://cdn.pixabay.com/photo/2015/01/09/11/08/startup-594090_1280.jpg',
    publishedAt: '2026-04-18T08:00:00Z',
    category: 'kenya',
  },
  {
    id: '2',
    title: 'NSE 20 Index Reaches 6-Month High Amid Banking Sector Rally',
    source: 'The Standard',
    summary: 'Kenyan stocks continue their upward momentum as banking sector heavyweights lead gains on the Nairobi Securities Exchange.',
    url: '#',
    imageUrl: 'https://cdn.pixabay.com/photo/2016/11/27/21/42/stock-1863880_1280.jpg',
    publishedAt: '2026-04-18T06:30:00Z',
    category: 'kenya',
  },
  {
    id: '3',
    title: 'Fed Signals Potential Rate Cut in June, Markets React Positively',
    source: 'Reuters',
    summary: 'US Federal Reserve hints at easing monetary policy as inflation shows signs of cooling, boosting global equities.',
    url: '#',
    imageUrl: 'https://cdn.pixabay.com/photo/2017/09/07/08/54/money-2724241_1280.jpg',
    publishedAt: '2026-04-17T22:00:00Z',
    category: 'global',
  },
  {
    id: '4',
    title: 'CBK Maintains Key Rate at 12.75%, Signals Cautious Outlook',
    source: 'Nation',
    summary: 'Central Bank of Kenya keeps benchmark rate unchanged citing persistent inflationary pressures and currency volatility concerns.',
    url: '#',
    imageUrl: 'https://cdn.pixabay.com/photo/2017/08/30/07/56/money-2696228_1280.jpg',
    publishedAt: '2026-04-17T14:00:00Z',
    category: 'kenya',
  },
  {
    id: '5',
    title: 'Apple Unveils AI-Powered iPhone 17, Stock Jumps 4%',
    source: 'Bloomberg',
    summary: 'Tech giant reveals next-generation smartphone with advanced AI capabilities, driving shares to new all-time highs.',
    url: '#',
    imageUrl: 'https://cdn.pixabay.com/photo/2014/08/05/10/30/iphone-410324_1280.jpg',
    publishedAt: '2026-04-17T18:00:00Z',
    category: 'global',
  },
  {
    id: '6',
    title: 'Kenya Infrastructure Bond Oversubscribed by 180%',
    source: 'Business Daily',
    summary: 'Government infrastructure bond sees massive demand from both local and foreign investors seeking stable returns.',
    url: '#',
    imageUrl: 'https://cdn.pixabay.com/photo/2017/01/30/02/20/bridge-2019972_1280.jpg',
    publishedAt: '2026-04-16T10:00:00Z',
    category: 'kenya',
  },
]

export const mockMarketIndices: MarketIndex[] = [
  { name: 'NSE 20', value: 1842.56, change: 12.34, changePercent: 0.67, currency: 'KES' },
  { name: 'NSE All Share', value: 108.45, change: 0.89, changePercent: 0.83, currency: 'KES' },
  { name: 'S&P 500', value: 5234.18, change: 28.45, changePercent: 0.55, currency: 'USD' },
  { name: 'NASDAQ', value: 16589.34, change: -42.12, changePercent: -0.25, currency: 'USD' },
  { name: 'FTSE 100', value: 8012.45, change: 18.90, changePercent: 0.24, currency: 'GBP' },
  { name: 'EUR/KES', value: 142.85, change: 0.45, changePercent: 0.32, currency: 'KES' },
  { name: 'USD/KES', value: 129.50, change: -0.25, changePercent: -0.19, currency: 'KES' },
]

export const mockStockPicks: StockPick[] = [
  {
    id: '1',
    ticker: 'SCOM',
    market: 'NSE',
    title: 'Safaricom - Strong Buy on M-Pesa Growth',
    commentary: 'With M-Pesa revenue growing at 18% YoY and expansion into Ethiopia gaining traction, Safaricom remains the cornerstone of any Kenyan portfolio. Current valuations offer attractive entry points.',
    sentiment: 'buy',
    isPro: false,
    publishedAt: '2026-04-18T08:00:00Z',
    learningBite: {
      id: 'lb1',
      topic: 'What is P/E Ratio?',
      explanation: 'Price-to-Earnings ratio shows how much investors pay for each shilling of company profits. A lower P/E might mean a stock is undervalued, but always compare within the same industry.',
      linkedInsightId: '1',
      isRead: false,
    },
  },
  {
    id: '2',
    ticker: 'EQTY',
    market: 'NSE',
    title: 'Equity Group - Regional Expansion Pays Off',
    commentary: 'Equity continues to deliver strong results across its East African operations. The digital banking transformation is reducing costs while expanding reach. Hold for long-term growth.',
    sentiment: 'hold',
    isPro: true,
    publishedAt: '2026-04-17T08:00:00Z',
    learningBite: {
      id: 'lb2',
      topic: 'Understanding Bank NIMs',
      explanation: 'Net Interest Margin (NIM) is the difference between what banks earn from loans and pay on deposits. Higher NIMs usually mean better profitability for banks.',
      linkedInsightId: '2',
      isRead: true,
    },
  },
  {
    id: '3',
    ticker: 'AAPL',
    market: 'NASDAQ',
    title: 'Apple - AI Features Drive New Growth Cycle',
    commentary: 'The new iPhone 17 with advanced AI capabilities positions Apple for another growth cycle. Consider dollar-cost averaging into this position for long-term wealth building.',
    sentiment: 'buy',
    isPro: true,
    publishedAt: '2026-04-16T08:00:00Z',
  },
  {
    id: '4',
    ticker: 'KCB',
    market: 'NSE',
    title: 'KCB Group - Watch for Entry Point',
    commentary: 'KCB is navigating challenges in some regional markets but fundamentals remain solid. Wait for a pullback to KES 38-40 range for optimal entry.',
    sentiment: 'watch',
    isPro: true,
    publishedAt: '2026-04-15T08:00:00Z',
    learningBite: {
      id: 'lb4',
      topic: 'Dollar-Cost Averaging',
      explanation: 'Instead of investing all your money at once, DCA means investing fixed amounts regularly. This reduces the risk of buying at market peaks.',
      linkedInsightId: '4',
      isRead: false,
    },
  },
]

export const mockVideos: VideoContent[] = [
  {
    id: '1',
    title: 'How to Build a Diversified Portfolio in Kenya',
    description: 'Learn the fundamentals of portfolio diversification with Kenya-specific examples and strategies.',
    thumbnailUrl: 'https://cdn.pixabay.com/photo/2016/11/27/21/42/stock-1863880_1280.jpg',
    videoUrl: '#',
    duration: '12:34',
    category: 'education',
    publishedAt: '2026-04-15T10:00:00Z',
  },
  {
    id: '2',
    title: 'NSE Weekly Roundup - April Week 3',
    description: 'A comprehensive analysis of this week top movers on the Nairobi Securities Exchange.',
    thumbnailUrl: 'https://cdn.pixabay.com/photo/2015/01/09/11/08/startup-594090_1280.jpg',
    videoUrl: '#',
    duration: '8:45',
    category: 'analysis',
    publishedAt: '2026-04-17T18:00:00Z',
  },
  {
    id: '3',
    title: 'Understanding Money Market Funds',
    description: 'Everything you need to know about MMFs and why they should be part of your investment strategy.',
    thumbnailUrl: 'https://cdn.pixabay.com/photo/2017/09/07/08/54/money-2724241_1280.jpg',
    videoUrl: '#',
    duration: '15:20',
    category: 'education',
    publishedAt: '2026-04-14T10:00:00Z',
  },
  {
    id: '4',
    title: 'Interview: CEO of Equity Group on Banking Future',
    description: 'Exclusive interview discussing the future of banking in East Africa and digital transformation.',
    thumbnailUrl: 'https://cdn.pixabay.com/photo/2015/07/17/22/43/student-849822_1280.jpg',
    videoUrl: '#',
    duration: '25:10',
    category: 'interview',
    publishedAt: '2026-04-12T10:00:00Z',
  },
]

export const mockCommunityPosts: CommunityPost[] = [
  {
    id: '1',
    authorName: 'James Kamau',
    content: 'Just hit my first KES 1M portfolio milestone! Started investing 3 years ago with just KES 5,000/month. Consistency is key!',
    likes: 124,
    comments: 32,
    publishedAt: '2026-04-18T10:00:00Z',
    isPinned: true,
  },
  {
    id: '2',
    authorName: 'Sarah Wanjiru',
    content: 'Anyone else bullish on Safaricom after the Q3 results? M-Pesa growth numbers were impressive. Thinking of increasing my position.',
    likes: 45,
    comments: 18,
    publishedAt: '2026-04-18T08:30:00Z',
  },
  {
    id: '3',
    authorName: 'David Ochieng',
    content: 'Pro tip for diaspora investors: Always factor in currency conversion costs when calculating returns. The USD/KES rate can significantly impact your actual gains.',
    likes: 89,
    comments: 12,
    publishedAt: '2026-04-17T22:00:00Z',
  },
  {
    id: '4',
    authorName: 'Grace Muthoni',
    content: 'Question for the community: What percentage of your portfolio do you allocate to global stocks vs NSE? Trying to find the right balance.',
    likes: 34,
    comments: 28,
    publishedAt: '2026-04-17T16:00:00Z',
  },
  {
    id: '5',
    authorName: 'Peter Njoroge',
    content: 'Just opened a Scope Markets account through Growe. The process was seamless. Now I can finally invest in US stocks directly!',
    likes: 67,
    comments: 15,
    publishedAt: '2026-04-17T12:00:00Z',
  },
]
